channels:
  - conda-forge
  - nodefaults
dependencies:
  - black
  - cftime
  - dask
  - esmf=*=nompi_*
  - esmpy
  - f90nml
  - flake8
  - gdal
  - geovista
  - hdf5=*=nompi_*
  - iris-esmf-regrid
  - iris-sample-data
  - iris
  - isort
  - libnetcdf!=4.9.1=nompi_*
  - mo_pack
  - nccmp
  - netcdf-fortran=*=nompi_*
  - numba
  - numpy=2.3.5
  - pre-commit
  - pydata-sphinx-theme
  - pyflakes
  - pykdtree
  - pytest
  - pytest-cov
  - pytest-xdist
  - python-stratify
  - python=3.12.12
  - ruff
  - setuptools
  - setuptools-scm
  - sphinx
  - sphinx-argparse
  - sphinx-copybutton
  - sphinx-sitemap
  - vtk=*=qt_*  # required for geovista on Met Office systems
