[command]
default=ants-launch plot_wrapper.sh $TARGET_ANA_TASK_WORK_DIR

[env]
PATH_PREPEND=${CYLC_WORKFLOW_SHARE_DIR}/fcm_make_ants/build/utils/plot_comparisons

[file:${CYLC_WORKFLOW_SHARE_DIR}/plot_comparisons]
mode=mkdir
