[command]
default=ants-launch ancil_create_shapefile.py ${SHAPEFILE_JSON} ${OUTPUT} --target-lsm ${LSM}

[env]
OUTPUT=${ROSE_DATA}/ite.shp
SHAPEFILE_JSON=${TEST_SOURCES_DIR}/ancil_create_shapefile/ite.json
LSM=/home/users/alasdair.roy/Documents/cartopy_tutorial/target_lsm.nc
