mode=rose_bunch

[bunch]
command-format=ants-launch ants_compare_files.sh $source_dir/%(filelist)s $target_dir/%(filelist)s
pool-size=12
names=$filelist

[bunch-args]
filelist=$filelist

[env]
source_dir=${ROSE_DATA}
target_dir=${TEST_RESULTS_DIR}
