[env]
filelist=ancil_general_regrid_grid_to_grid_latitude_weighted_kdtree_split0
        =ancil_general_regrid_grid_to_grid_latitude_weighted_kdtree_split1
        =ancil_general_regrid_grid_to_grid_latitude_weighted_kdtree_split2
        =ancil_general_regrid_with_time_constraint_latitude_weighted_kdtree_split0
        =ancil_general_regrid_with_time_constraint_latitude_weighted_kdtree_split1
        =ancil_general_regrid_with_time_constraint_latitude_weighted_kdtree_split2
        =ancil_general_regrid_invert_mask_latitude_weighted_kdtree_split0
        =ancil_general_regrid_invert_mask_latitude_weighted_kdtree_split1
        =ancil_general_regrid_invert_mask_latitude_weighted_kdtree_split2
        =ancil_general_regrid_grid_to_grid_latitude_weighted_kdtree_split0.nc
        =ancil_general_regrid_grid_to_grid_latitude_weighted_kdtree_split1.nc
        =ancil_general_regrid_grid_to_grid_latitude_weighted_kdtree_split2.nc
        =ancil_general_regrid_with_time_constraint_latitude_weighted_kdtree_split0.nc
        =ancil_general_regrid_with_time_constraint_latitude_weighted_kdtree_split1.nc
        =ancil_general_regrid_with_time_constraint_latitude_weighted_kdtree_split2.nc
        =ancil_general_regrid_invert_mask_latitude_weighted_kdtree_split0.nc
        =ancil_general_regrid_invert_mask_latitude_weighted_kdtree_split1.nc
        =ancil_general_regrid_invert_mask_latitude_weighted_kdtree_split2.nc
