[env]
filelist=ancil_general_regrid_grid_to_grid_spiral_split1
        =ancil_general_regrid_with_time_constraint_spiral_split1
        =ancil_general_regrid_grid_to_grid_spiral_split2
        =ancil_general_regrid_with_time_constraint_spiral_split2
        =ancil_general_regrid_grid_to_grid_spiral_split0
        =ancil_general_regrid_with_time_constraint_spiral_split0
        =ancil_general_regrid_invert_mask_spiral_split0
        =ancil_general_regrid_invert_mask_spiral_split1
        =ancil_general_regrid_invert_mask_spiral_split2
        =ancil_general_regrid_grid_to_grid_spiral_split1.nc
        =ancil_general_regrid_with_time_constraint_spiral_split1.nc
        =ancil_general_regrid_grid_to_grid_spiral_split2.nc
        =ancil_general_regrid_with_time_constraint_spiral_split2.nc
        =ancil_general_regrid_grid_to_grid_spiral_split0.nc
        =ancil_general_regrid_with_time_constraint_spiral_split0.nc
        =ancil_general_regrid_invert_mask_spiral_split0.nc
        =ancil_general_regrid_invert_mask_spiral_split1.nc
        =ancil_general_regrid_invert_mask_spiral_split2.nc
